#!/bin/bash
cd
if [ $(id -u) != 0 ]
then
echo "Ejecute el script como root"
exit
fi
echo -e "\033[1;30mInstalando...\033[0m"
mkdir /etc/vpsdirectorio 2>/dev/null
mkdir /etc/vpsdirectorio/limite 2>/dev/null
mkdir /etc/vpsdirectorio/contraseña 2>/dev/null
rm -rf /bin/vps 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/angelbanderasl/vps/master/vps > /bin/vps
chmod +x /bin/vps
rm -rf /bin/limite 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/angelbanderasl/vps/master/limite > /bin/limite
chmod +x /bin/limite
rm -rf /bin/crearusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/angelbanderasl/vps/master/crearusuario > /bin/crearusuario
chmod +x /bin/crearusuario
rm -rf /bin/eliminarusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/angelbanderasl/vps/master/eliminarusuario > /bin/eliminarusuario
chmod +x /bin/eliminarusuario
rm -rf /bin/redefinirusuario 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/angelbanderasl/vps/master/redefinirusuario > /bin/redefinirusuario
chmod +x /bin/redefinirusuario
rm -rf /bin/speedtest.py 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/angelbanderasl/vps/master/speedtest.py > /bin/speedtest.py
chmod +x /bin/speedtest.py
rm -rf badvpn 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/angelbanderasl/vps/master/badvpn > badvpn
chmod +x badvpn
rm -rf /bin/@actualiza 2>/dev/null
wget -o /dev/null -O- https://raw.githubusercontent.com/angelbanderasl/vps/master/@actualiza > /bin/@actualiza
chmod +x /bin/@actualiza
clear
echo -e "\033[1;32mInstalacion Finalizada\n\033[1;30mEjecute:"
echo -e "\n\033[1;32mvps \033[1;30mMenu de opciones"
echo -e "\033[1;32mCreada por: \033[1;30mAngel Banderas"
echo -e "\033[1;32mInstalada \033[1;30mVersion 0.1\033[0m"
echo -e "\033[1;32mPuedes actualizar con \033[1;30m@actualiza\033[0m"
echo -e "\033[1;32mProbar velocidad con \033[1;30mOpcion 2\033[0m"
rm -rf install
