#!/bin/bash
function sshd_config(){
echo "
Port 443
PermitRootLogin yes
PubkeyAuthentication yes
PasswordAuthentication yes
Banner /etc/bannerssh
" >> /etc/ssh/sshd_config
}
function configurarsquid(){
echo -e "\033[1;31mPara que la instalacion sea correcta se necesita una ip.
Digite su ip !\033[0m"
read -p ": " ip
echo -e "\033[1;37mConfigurando, Espere...\033[0m"
apt-get update 1> /dev/null 2> /dev/null
apt-get install -y squid3 1> /dev/null 2> /dev/null

service apache2 stop 1> /dev/null 2> /dev/null
chattr -i /etc/ssh/sshd_config > /dev/null 2> /dev/null
sshd_config
service ssh restart 1> /dev/null 2> /dev/null

echo "http_port 80
http_port 8080
http_port 8799
http_port 3128
visible_hostname vpsadmin
acl ip dstdomain $ip
http_access allow ip" > /etc/squid/squid.conf
echo 'acl accept dstdomain -i "/etc/payloads"
http_access allow accept
acl local dstdomain localhost
http_access allow local
acl iplocal dstdomain 127.0.0.1
http_access allow iplocal
http_access deny all' >> /etc/squid/squid.conf
service squid restart 1> /dev/null 2> /dev/null
echo -e "\033[01;31mFinalizado !! \033[0m"
exit 0
}
function dropbear(){
apt-get -y install dropbear
sed -i 's/NO_START=1/NO_START=0/g' /etc/default/dropbear
sed -i 's/DROPBEAR_PORT=22/DROPBEAR_PORT=444/g' /etc/default/dropbear
sed -i 's/DROPBEAR_EXTRA_ARGS=/DROPBEAR_EXTRA_ARGS="-p 80"/g' /etc/default/dropbear
echo "/bin/false" >> /etc/shells
echo "/usr/sbin/nologin" >> /etc/shells
service ssh restart
service dropbear restart
}
clear
if [[ $1 == "" ]]
then
echo -e "\033[1;37m    Administrador Vps para ubuntu 16.04 © MX (Angel Banderas) \033[0m"
echo -e "\033[1;37mSeleccione una opcion:    Para Salir pulse Ctrl + C\033[0;32m
[\033[1;30m01\033[0;32m] Squid_SSH_Dropbear... \033[1;30m(Squid, OpenSSH, Dropbear, Shadowsocks y BadVpn)\033[0;32m
[\033[1;30m02\033[0;32m] Speedtest \033[1;30m(Prueba de conexion [velocidad de banda])\033[0;32m
[\033[1;30m03\033[0;32m] Ver_Puertos \033[1;30m(Ver puertos abiertos)\033[0;32m
[\033[1;30m04\033[0;32m] Crear_Usuario \033[1;30m(Crear usuarios)\033[0;32m
[\033[1;30m05\033[0;32m] Dropbear \033[1;30m(Dropbear)\033[0;32m
[\033[1;30m06\033[0;32m] Eliminar_Usuario \033[1;30m(Menu Eliminar, Desconectar, etc)\033[0;32m
[\033[1;30m07\033[0;32m] Redefinir_Usuario \033[1;30m(Cambiar fecha, contraseña, etc)\033[0;32m"

read -p ": " opcion
else
opcion=$1
fi
case $opcion in
  1 | 01 )
   configurarsquid;;
  2 | 02 )
  apt install python -y
  speedtest.py;;
  3 | 03 )
  netstat -tunlp;;
  4 | 04 )
  crearusuario;;
  5 | 05 ) 
  dropbear;;
  6 | 06 ) 
  eliminarusuario;;
  7 | 07 ) 
  redefinirusuario;;
esac
