#!/bin/bash
function ssh_config(){
echo 'Port 443
PermitRootLogin yes
PubkeyAuthentication yes
PasswordAuthentication yes
' >> /etc/ssh/sshd_config
}
echo -e "\033[1;37m    Administrador Vps para ubuntu 16.04 © MX (Angel Banderas) \033[0m"
echo -e "\033[1;37mSeleccione una opcion:    Para Salir pulse Ctrl + C\033[0;32m
[\033[1;30m01\033[0;32m] Squid_SSH_Dropbear... \033[1;30m(Squid, OpenSSH, Dropbear, Shadowsocks y BadVpn)\033[0;32m
read -p ": " opcion
else
opcion=$1
fi
case $opcion in
  1 | 01 )
   ssh_config;;
esac
